version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SEGREDO_JWT: ${SEGREDO_JWT}
      SAL_SENHA: ${SAL_SENHA}
    ports:
      - "8000:8000"
    networks:
      - backend
  
  # redis:
  #  container_name: redis-cache
  #  image: redis:7.0-alpine
  #  ports:
  #    - "6379:6379"
  #  volumes:
  #    - redis:/data
  #  networks:
  #    - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres:
